# coding: utf-8

"""
    HPE Aruba Networking UXI Configuration

    This document outlines the API contracts for HPE Aruba Networking UXI.

    The version of the OpenAPI document: 6.6.0
    Contact: support@capenetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyhpeuxi.models.sensor_group_assignments_get_item import SensorGroupAssignmentsGetItem

class TestSensorGroupAssignmentsGetItem(unittest.TestCase):
    """SensorGroupAssignmentsGetItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SensorGroupAssignmentsGetItem:
        """Test SensorGroupAssignmentsGetItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SensorGroupAssignmentsGetItem`
        """
        model = SensorGroupAssignmentsGetItem()
        if include_optional:
            return SensorGroupAssignmentsGetItem(
                id = '',
                group = pyhpeuxi.models.sensor_group_assignments_get_group.SensorGroupAssignmentsGetGroup(
                    id = '', ),
                sensor = pyhpeuxi.models.sensor_group_assignments_get_sensor.SensorGroupAssignmentsGetSensor(
                    id = '', ),
                type = 'networking-uxi/sensor-group-assignment'
            )
        else:
            return SensorGroupAssignmentsGetItem(
                id = '',
                group = pyhpeuxi.models.sensor_group_assignments_get_group.SensorGroupAssignmentsGetGroup(
                    id = '', ),
                sensor = pyhpeuxi.models.sensor_group_assignments_get_sensor.SensorGroupAssignmentsGetSensor(
                    id = '', ),
                type = 'networking-uxi/sensor-group-assignment',
        )
        """

    def testSensorGroupAssignmentsGetItem(self):
        """Test SensorGroupAssignmentsGetItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
