# coding: utf-8

"""
    HPE Aruba Networking UXI Configuration

    This document outlines the API contracts for HPE Aruba Networking UXI.

    The version of the OpenAPI document: 6.6.0
    Contact: support@capenetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyhpeuxi.api.api_api import ApiApi


class TestApiApi(unittest.TestCase):
    """ApiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApiApi()

    def tearDown(self) -> None:
        pass

    def test_agent_delete(self) -> None:
        """Test case for agent_delete

        Agent Delete
        """
        pass

    def test_agent_group_assignment_delete(self) -> None:
        """Test case for agent_group_assignment_delete

        Agent Group Assignment Delete
        """
        pass

    def test_agent_group_assignment_post(self) -> None:
        """Test case for agent_group_assignment_post

        Agent Group Assignment Post
        """
        pass

    def test_agent_group_assignments_get(self) -> None:
        """Test case for agent_group_assignments_get

        Agent Group Assignments Get
        """
        pass

    def test_agent_patch(self) -> None:
        """Test case for agent_patch

        Agent Patch
        """
        pass

    def test_agents_get(self) -> None:
        """Test case for agents_get

        Agents Get
        """
        pass

    def test_group_delete(self) -> None:
        """Test case for group_delete

        Group Delete
        """
        pass

    def test_group_patch(self) -> None:
        """Test case for group_patch

        Group Patch
        """
        pass

    def test_group_post(self) -> None:
        """Test case for group_post

        Group Post
        """
        pass

    def test_groups_get(self) -> None:
        """Test case for groups_get

        Groups Get
        """
        pass

    def test_network_group_assignment_delete(self) -> None:
        """Test case for network_group_assignment_delete

        Network Group Assignment Delete
        """
        pass

    def test_network_group_assignment_post(self) -> None:
        """Test case for network_group_assignment_post

        Network Group Assignment Post
        """
        pass

    def test_network_group_assignments_get(self) -> None:
        """Test case for network_group_assignments_get

        Network Group Assignments Get
        """
        pass

    def test_sensor_group_assignment_delete(self) -> None:
        """Test case for sensor_group_assignment_delete

        Sensor Group Assignment Delete
        """
        pass

    def test_sensor_group_assignment_post(self) -> None:
        """Test case for sensor_group_assignment_post

        Sensor Group Assignment Post
        """
        pass

    def test_sensor_group_assignments_get(self) -> None:
        """Test case for sensor_group_assignments_get

        Sensor Group Assignments Get
        """
        pass

    def test_sensor_patch(self) -> None:
        """Test case for sensor_patch

        Sensor Patch
        """
        pass

    def test_sensors_get(self) -> None:
        """Test case for sensors_get

        Sensors Get
        """
        pass

    def test_service_test_group_assignment_delete(self) -> None:
        """Test case for service_test_group_assignment_delete

        Service Test Group Assignment Delete
        """
        pass

    def test_service_test_group_assignment_post(self) -> None:
        """Test case for service_test_group_assignment_post

        Service Test Group Assignment Post
        """
        pass

    def test_service_test_group_assignments_get(self) -> None:
        """Test case for service_test_group_assignments_get

        Service Test Group Assignments Get
        """
        pass

    def test_service_tests_get(self) -> None:
        """Test case for service_tests_get

        Service Tests Get
        """
        pass

    def test_wired_networks_get(self) -> None:
        """Test case for wired_networks_get

        Wired Networks Get
        """
        pass

    def test_wireless_networks_get(self) -> None:
        """Test case for wireless_networks_get

        Wireless Networks Get
        """
        pass


if __name__ == '__main__':
    unittest.main()
