# coding: utf-8

"""
    HPE Aruba Networking UXI Configuration

    This document outlines the API contracts for HPE Aruba Networking UXI.

    The version of the OpenAPI document: 6.6.0
    Contact: support@capenetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyhpeuxi.api.sensor_group_assignments_api import SensorGroupAssignmentsApi


class TestSensorGroupAssignmentsApi(unittest.TestCase):
    """SensorGroupAssignmentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SensorGroupAssignmentsApi()

    def tearDown(self) -> None:
        pass

    def test_sensor_group_assignment_delete(self) -> None:
        """Test case for sensor_group_assignment_delete

        Sensor Group Assignment Delete
        """
        pass

    def test_sensor_group_assignment_post(self) -> None:
        """Test case for sensor_group_assignment_post

        Sensor Group Assignment Post
        """
        pass

    def test_sensor_group_assignments_get(self) -> None:
        """Test case for sensor_group_assignments_get

        Sensor Group Assignments Get
        """
        pass


if __name__ == '__main__':
    unittest.main()
