# coding: utf-8

"""
    HPE Aruba Networking UXI Configuration

    This document outlines the API contracts for HPE Aruba Networking UXI.

    The version of the OpenAPI document: 6.6.0
    Contact: support@capenetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyhpeuxi.api.agent_group_assignments_api import AgentGroupAssignmentsApi


class TestAgentGroupAssignmentsApi(unittest.TestCase):
    """AgentGroupAssignmentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AgentGroupAssignmentsApi()

    def tearDown(self) -> None:
        pass

    def test_agent_group_assignment_delete(self) -> None:
        """Test case for agent_group_assignment_delete

        Agent Group Assignment Delete
        """
        pass

    def test_agent_group_assignment_post(self) -> None:
        """Test case for agent_group_assignment_post

        Agent Group Assignment Post
        """
        pass

    def test_agent_group_assignments_get(self) -> None:
        """Test case for agent_group_assignments_get

        Agent Group Assignments Get
        """
        pass


if __name__ == '__main__':
    unittest.main()
