# coding: utf-8

"""
    HPE Aruba Networking UXI Configuration

    This document outlines the API contracts for HPE Aruba Networking UXI.

    The version of the OpenAPI document: 6.6.0
    Contact: support@capenetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyhpeuxi.api.sensors_api import SensorsApi


class TestSensorsApi(unittest.TestCase):
    """SensorsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SensorsApi()

    def tearDown(self) -> None:
        pass

    def test_sensor_patch(self) -> None:
        """Test case for sensor_patch

        Sensor Patch
        """
        pass

    def test_sensors_get(self) -> None:
        """Test case for sensors_get

        Sensors Get
        """
        pass


if __name__ == '__main__':
    unittest.main()
