# coding: utf-8

"""
    HPE Aruba Networking UXI Configuration

    This document outlines the API contracts for HPE Aruba Networking UXI.

    The version of the OpenAPI document: 6.6.0
    Contact: support@capenetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyhpeuxi.models.sensor_group_assignment_post_response import SensorGroupAssignmentPostResponse

class TestSensorGroupAssignmentPostResponse(unittest.TestCase):
    """SensorGroupAssignmentPostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SensorGroupAssignmentPostResponse:
        """Test SensorGroupAssignmentPostResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SensorGroupAssignmentPostResponse`
        """
        model = SensorGroupAssignmentPostResponse()
        if include_optional:
            return SensorGroupAssignmentPostResponse(
                id = '',
                group = pyhpeuxi.models.sensor_group_assignment_post_group.SensorGroupAssignmentPostGroup(
                    id = '', ),
                sensor = pyhpeuxi.models.sensor_group_assignment_post_sensor.SensorGroupAssignmentPostSensor(
                    id = '', ),
                type = 'networking-uxi/sensor-group-assignment'
            )
        else:
            return SensorGroupAssignmentPostResponse(
                id = '',
                group = pyhpeuxi.models.sensor_group_assignment_post_group.SensorGroupAssignmentPostGroup(
                    id = '', ),
                sensor = pyhpeuxi.models.sensor_group_assignment_post_sensor.SensorGroupAssignmentPostSensor(
                    id = '', ),
                type = 'networking-uxi/sensor-group-assignment',
        )
        """

    def testSensorGroupAssignmentPostResponse(self):
        """Test SensorGroupAssignmentPostResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
