#
# Copyright 2025 Hewlett Packard Enterprise Development LP.
#

# coding: utf-8

"""
    HPE Aruba Networking UXI Configuration

    This document outlines the API contracts for HPE Aruba Networking UXI.

    The version of the OpenAPI document: 6.6.0
    Contact: support@capenetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyhpeuxi.models.service_test_group_assignments_get_response import ServiceTestGroupAssignmentsGetResponse

class TestServiceTestGroupAssignmentsGetResponse(unittest.TestCase):
    """ServiceTestGroupAssignmentsGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceTestGroupAssignmentsGetResponse:
        """Test ServiceTestGroupAssignmentsGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceTestGroupAssignmentsGetResponse`
        """
        model = ServiceTestGroupAssignmentsGetResponse()
        if include_optional:
            return ServiceTestGroupAssignmentsGetResponse(
                items = [
                    pyhpeuxi.models.service_test_group_assignments_get_item.ServiceTestGroupAssignmentsGetItem(
                        id = '', 
                        group = pyhpeuxi.models.service_test_group_assignments_get_group.ServiceTestGroupAssignmentsGetGroup(
                            id = '', ), 
                        service_test = pyhpeuxi.models.service_test_group_assignments_get_service_test.ServiceTestGroupAssignmentsGetServiceTest(
                            id = '', ), 
                        type = 'networking-uxi/service-test-group-assignment', )
                    ],
                count = 56,
                next = ''
            )
        else:
            return ServiceTestGroupAssignmentsGetResponse(
                items = [
                    pyhpeuxi.models.service_test_group_assignments_get_item.ServiceTestGroupAssignmentsGetItem(
                        id = '', 
                        group = pyhpeuxi.models.service_test_group_assignments_get_group.ServiceTestGroupAssignmentsGetGroup(
                            id = '', ), 
                        service_test = pyhpeuxi.models.service_test_group_assignments_get_service_test.ServiceTestGroupAssignmentsGetServiceTest(
                            id = '', ), 
                        type = 'networking-uxi/service-test-group-assignment', )
                    ],
                count = 56,
                next = '',
        )
        """

    def testServiceTestGroupAssignmentsGetResponse(self):
        """Test ServiceTestGroupAssignmentsGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
