# coding: utf-8

"""
    HPE Aruba Networking UXI Configuration

    This document outlines the API contracts for HPE Aruba Networking UXI.

    The version of the OpenAPI document: 6.6.0
    Contact: support@capenetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyhpeuxi.api.service_tests_api import ServiceTestsApi


class TestServiceTestsApi(unittest.TestCase):
    """ServiceTestsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServiceTestsApi()

    def tearDown(self) -> None:
        pass

    def test_service_tests_get(self) -> None:
        """Test case for service_tests_get

        Service Tests Get
        """
        pass


if __name__ == '__main__':
    unittest.main()
