#
# Copyright 2025 Hewlett Packard Enterprise Development LP.
#

# coding: utf-8

"""
    HPE Aruba Networking UXI Configuration

    This document outlines the API contracts for HPE Aruba Networking UXI.

    The version of the OpenAPI document: 6.6.0
    Contact: support@capenetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyhpeuxi.models.sensor_pcap_mode import SensorPcapMode

class TestSensorPcapMode(unittest.TestCase):
    """SensorPcapMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSensorPcapMode(self):
        """Test SensorPcapMode"""
        # inst = SensorPcapMode()

if __name__ == '__main__':
    unittest.main()
