#
# Copyright 2025 Hewlett Packard Enterprise Development LP.
#

# coding: utf-8

"""
    HPE Aruba Networking UXI Configuration

    This document outlines the API contracts for HPE Aruba Networking UXI.

    The version of the OpenAPI document: 6.6.0
    Contact: support@capenetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyhpeuxi.models.wireless_networks_get_response import WirelessNetworksGetResponse

class TestWirelessNetworksGetResponse(unittest.TestCase):
    """WirelessNetworksGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WirelessNetworksGetResponse:
        """Test WirelessNetworksGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WirelessNetworksGetResponse`
        """
        model = WirelessNetworksGetResponse()
        if include_optional:
            return WirelessNetworksGetResponse(
                items = [
                    pyhpeuxi.models.wireless_networks_get_item.WirelessNetworksGetItem(
                        id = '', 
                        name = '', 
                        ssid = '', 
                        security = '', 
                        ip_version = 'ipv4', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        hidden = True, 
                        band_locking = '', 
                        dns_lookup_domain = '', 
                        disable_edns = True, 
                        use_dns64 = True, 
                        external_connectivity = True, 
                        type = 'networking-uxi/wireless-network', )
                    ],
                count = 56,
                next = ''
            )
        else:
            return WirelessNetworksGetResponse(
                items = [
                    pyhpeuxi.models.wireless_networks_get_item.WirelessNetworksGetItem(
                        id = '', 
                        name = '', 
                        ssid = '', 
                        security = '', 
                        ip_version = 'ipv4', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        hidden = True, 
                        band_locking = '', 
                        dns_lookup_domain = '', 
                        disable_edns = True, 
                        use_dns64 = True, 
                        external_connectivity = True, 
                        type = 'networking-uxi/wireless-network', )
                    ],
                count = 56,
                next = '',
        )
        """

    def testWirelessNetworksGetResponse(self):
        """Test WirelessNetworksGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
