# coding: utf-8

"""
    HPE Aruba Networking UXI Configuration

    This document outlines the API contracts for HPE Aruba Networking UXI.

    The version of the OpenAPI document: 6.6.0
    Contact: support@capenetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyhpeuxi.models.agent_patch_response import AgentPatchResponse

class TestAgentPatchResponse(unittest.TestCase):
    """AgentPatchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentPatchResponse:
        """Test AgentPatchResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentPatchResponse`
        """
        model = AgentPatchResponse()
        if include_optional:
            return AgentPatchResponse(
                id = '',
                serial = '',
                name = '',
                model_number = '',
                wifi_mac_address = '',
                ethernet_mac_address = '',
                notes = '',
                pcap_mode = 'light',
                type = 'networking-uxi/agent'
            )
        else:
            return AgentPatchResponse(
                id = '',
                serial = '',
                name = '',
                model_number = '',
                wifi_mac_address = '',
                ethernet_mac_address = '',
                notes = '',
                pcap_mode = 'light',
                type = 'networking-uxi/agent',
        )
        """

    def testAgentPatchResponse(self):
        """Test AgentPatchResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
