#
# Copyright 2025 Hewlett Packard Enterprise Development LP.
#

# coding: utf-8

"""
    HPE Aruba Networking UXI Configuration

    This document outlines the API contracts for HPE Aruba Networking UXI.

    The version of the OpenAPI document: 6.6.0
    Contact: support@capenetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyhpeuxi.api.wireless_networks_api import WirelessNetworksApi


class TestWirelessNetworksApi(unittest.TestCase):
    """WirelessNetworksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WirelessNetworksApi()

    def tearDown(self) -> None:
        pass

    def test_wireless_networks_get(self) -> None:
        """Test case for wireless_networks_get

        Wireless Networks Get
        """
        pass


if __name__ == '__main__':
    unittest.main()
