#
# Copyright 2025 Hewlett Packard Enterprise Development LP.
#

# coding: utf-8

"""
    HPE Aruba Networking UXI Configuration

    This document outlines the API contracts for HPE Aruba Networking UXI.

    The version of the OpenAPI document: 6.6.0
    Contact: support@capenetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyhpeuxi.models.agents_get_response import AgentsGetResponse

class TestAgentsGetResponse(unittest.TestCase):
    """AgentsGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentsGetResponse:
        """Test AgentsGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentsGetResponse`
        """
        model = AgentsGetResponse()
        if include_optional:
            return AgentsGetResponse(
                items = [
                    pyhpeuxi.models.agents_get_item.AgentsGetItem(
                        id = '', 
                        serial = '', 
                        name = '', 
                        model_number = '', 
                        wifi_mac_address = '', 
                        ethernet_mac_address = '', 
                        notes = '', 
                        pcap_mode = 'light', 
                        type = 'networking-uxi/agent', )
                    ],
                count = 56,
                next = ''
            )
        else:
            return AgentsGetResponse(
                items = [
                    pyhpeuxi.models.agents_get_item.AgentsGetItem(
                        id = '', 
                        serial = '', 
                        name = '', 
                        model_number = '', 
                        wifi_mac_address = '', 
                        ethernet_mac_address = '', 
                        notes = '', 
                        pcap_mode = 'light', 
                        type = 'networking-uxi/agent', )
                    ],
                count = 56,
                next = '',
        )
        """

    def testAgentsGetResponse(self):
        """Test AgentsGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
