#
# Copyright 2025 Hewlett Packard Enterprise Development LP.
#

# coding: utf-8

"""
    HPE Aruba Networking UXI Configuration

    This document outlines the API contracts for HPE Aruba Networking UXI.

    The version of the OpenAPI document: 6.6.0
    Contact: support@capenetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyhpeuxi.api.service_test_group_assignments_api import ServiceTestGroupAssignmentsApi


class TestServiceTestGroupAssignmentsApi(unittest.TestCase):
    """ServiceTestGroupAssignmentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServiceTestGroupAssignmentsApi()

    def tearDown(self) -> None:
        pass

    def test_service_test_group_assignment_delete(self) -> None:
        """Test case for service_test_group_assignment_delete

        Service Test Group Assignment Delete
        """
        pass

    def test_service_test_group_assignment_post(self) -> None:
        """Test case for service_test_group_assignment_post

        Service Test Group Assignment Post
        """
        pass

    def test_service_test_group_assignments_get(self) -> None:
        """Test case for service_test_group_assignments_get

        Service Test Group Assignments Get
        """
        pass


if __name__ == '__main__':
    unittest.main()
