# coding: utf-8

"""
    HPE Aruba Networking UXI Configuration

    This document outlines the API contracts for HPE Aruba Networking UXI.

    The version of the OpenAPI document: 6.6.0
    Contact: support@capenetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyhpeuxi.api.groups_api import GroupsApi


class TestGroupsApi(unittest.TestCase):
    """GroupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GroupsApi()

    def tearDown(self) -> None:
        pass

    def test_group_delete(self) -> None:
        """Test case for group_delete

        Group Delete
        """
        pass

    def test_group_patch(self) -> None:
        """Test case for group_patch

        Group Patch
        """
        pass

    def test_group_post(self) -> None:
        """Test case for group_post

        Group Post
        """
        pass

    def test_groups_get(self) -> None:
        """Test case for groups_get

        Groups Get
        """
        pass


if __name__ == '__main__':
    unittest.main()
