#
# Copyright 2025 Hewlett Packard Enterprise Development LP.
#

# coding: utf-8

"""
    HPE Aruba Networking UXI Configuration

    This document outlines the API contracts for HPE Aruba Networking UXI.

    The version of the OpenAPI document: 6.6.0
    Contact: support@capenetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyhpeuxi.api.agents_api import AgentsApi


class TestAgentsApi(unittest.TestCase):
    """AgentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AgentsApi()

    def tearDown(self) -> None:
        pass

    def test_agent_delete(self) -> None:
        """Test case for agent_delete

        Agent Delete
        """
        pass

    def test_agent_patch(self) -> None:
        """Test case for agent_patch

        Agent Patch
        """
        pass

    def test_agents_get(self) -> None:
        """Test case for agents_get

        Agents Get
        """
        pass


if __name__ == '__main__':
    unittest.main()
