# coding: utf-8

"""
    HPE Aruba Networking UXI Configuration

    This document outlines the API contracts for HPE Aruba Networking UXI.

    The version of the OpenAPI document: 6.6.0
    Contact: support@capenetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pyhpeuxi.api.wired_networks_api import WiredNetworksApi


class TestWiredNetworksApi(unittest.TestCase):
    """WiredNetworksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WiredNetworksApi()

    def tearDown(self) -> None:
        pass

    def test_wired_networks_get(self) -> None:
        """Test case for wired_networks_get

        Wired Networks Get
        """
        pass


if __name__ == '__main__':
    unittest.main()
