#
# Copyright 2025 Hewlett Packard Enterprise Development LP.
#

# coding: utf-8

"""
    HPE Aruba Networking UXI Configuration

    This document outlines the API contracts for HPE Aruba Networking UXI.

    The version of the OpenAPI document: 6.5.0
    Contact: support@capenetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SensorPcapMode(str, Enum):
    """
    SensorPcapMode
    """

    """
    allowed enum values
    """
    LIGHT = 'light'
    FULL = 'full'
    OFF = 'off'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SensorPcapMode from a JSON string"""
        return cls(json.loads(json_str))


