# coding: utf-8

"""
    HPE Aruba Networking UXI Configuration

    This document outlines the API contracts for HPE Aruba Networking UXI.

    The version of the OpenAPI document: 6.5.0
    Contact: support@capenetworks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from pyhpeuxi.models.sensor_pcap_mode import SensorPcapMode
from typing import Optional, Set
from typing_extensions import Self

class SensorsGetItem(BaseModel):
    """
    SensorsGetItem
    """ # noqa: E501
    id: StrictStr = Field(description="The unique identifier of the sensor")
    serial: StrictStr = Field(description="The serial number of the sensor")
    name: StrictStr = Field(description="The name of the sensor")
    model_number: StrictStr = Field(description="The model number of the sensor", alias="modelNumber")
    wifi_mac_address: Optional[StrictStr] = Field(alias="wifiMacAddress")
    ethernet_mac_address: Optional[StrictStr] = Field(alias="ethernetMacAddress")
    address_note: Optional[StrictStr] = Field(alias="addressNote")
    longitude: Optional[Union[StrictFloat, StrictInt]]
    latitude: Optional[Union[StrictFloat, StrictInt]]
    notes: Optional[StrictStr]
    pcap_mode: Optional[SensorPcapMode] = Field(alias="pcapMode")
    type: StrictStr = Field(description="The type of the resource.")
    __properties: ClassVar[List[str]] = ["id", "serial", "name", "modelNumber", "wifiMacAddress", "ethernetMacAddress", "addressNote", "longitude", "latitude", "notes", "pcapMode", "type"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['networking-uxi/sensor']):
            raise ValueError("must be one of enum values ('networking-uxi/sensor')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SensorsGetItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if wifi_mac_address (nullable) is None
        # and model_fields_set contains the field
        if self.wifi_mac_address is None and "wifi_mac_address" in self.model_fields_set:
            _dict['wifiMacAddress'] = None

        # set to None if ethernet_mac_address (nullable) is None
        # and model_fields_set contains the field
        if self.ethernet_mac_address is None and "ethernet_mac_address" in self.model_fields_set:
            _dict['ethernetMacAddress'] = None

        # set to None if address_note (nullable) is None
        # and model_fields_set contains the field
        if self.address_note is None and "address_note" in self.model_fields_set:
            _dict['addressNote'] = None

        # set to None if longitude (nullable) is None
        # and model_fields_set contains the field
        if self.longitude is None and "longitude" in self.model_fields_set:
            _dict['longitude'] = None

        # set to None if latitude (nullable) is None
        # and model_fields_set contains the field
        if self.latitude is None and "latitude" in self.model_fields_set:
            _dict['latitude'] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict['notes'] = None

        # set to None if pcap_mode (nullable) is None
        # and model_fields_set contains the field
        if self.pcap_mode is None and "pcap_mode" in self.model_fields_set:
            _dict['pcapMode'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SensorsGetItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "serial": obj.get("serial"),
            "name": obj.get("name"),
            "modelNumber": obj.get("modelNumber"),
            "wifiMacAddress": obj.get("wifiMacAddress"),
            "ethernetMacAddress": obj.get("ethernetMacAddress"),
            "addressNote": obj.get("addressNote"),
            "longitude": obj.get("longitude"),
            "latitude": obj.get("latitude"),
            "notes": obj.get("notes"),
            "pcapMode": obj.get("pcapMode"),
            "type": obj.get("type")
        })
        return _obj


